### ISSUE TITLE
Support GKE v1.18

### ISSUE THREAD

**Issue by mangulonr** [newrelic/nri-kubernetes#103]
We need to test our Kubernetes integrations supports GKE v.1.18, we currently support until version 1.17 ([check doc.](https://docs.newrelic.com/docs/integrations/kubernetes-integration/get-started/kubernetes-integration-compatibility-requirements/#compatibility))

Tasks to be done:

- Check compatibility with GKE 1.18
- Update [documentation](https://docs.newrelic.com/docs/integrations/kubernetes-integration/get-started/kubernetes-integration-compatibility-requirements/#compatibility)

**Comment by ingernet** [comment]
1.18.17-gke.700 is now the default cluster version in GCP's stable channel. [1.17 will become unavailable in less than 3 months](https://cloud.google.com/kubernetes-engine/docs/release-schedule). Please prioritize this.

**Comment by roobre** [comment]
I have asserted that, to the extent of the available testing, we haven't seen any incompatibility between the latest availabe version of `nri-kubernetes` and a GKE 1.19 environment.

We will proceed to update the documentation to reflect this soon.
