### ISSUE TITLE
windows k8's monitoring, no data. 1.21.0 alpha

### ISSUE THREAD

**Issue by jayntguru** [newrelic/nri-kubernetes#12]
## Description

Tried 1.21 alpha. Pods start and run, and we can see the nodes in inventory but they are not sending back any data.

## Steps to Reproduce

Run 1.21.0 alpha for windows

## Expected Behavior

Data in new relic console

## Relevant Logs / Console output
[nrwindows.log](https://github.com/newrelic/nri-kubernetes/files/5030355/nrwindows.log)

Pod output is attached.

## Your Environment

Rancher provisioned cluster running kube 1.17.5. We have newrelic in place and working on the linux nodes, and ksm is running there.

## Additional context

We used the existing service account, namespace and ksm as the liux version that already exists.

**Comment by mfuentes-newrelic** [comment]
Hello @jayntguru !
Many thanks for reaching out! Are the Linux nodes reporting correctly? Also, could you share the Windows version?

**Comment by jayntguru** [comment]
Yes, we're long time users of the Linux integration, and in that same cluster we're getting data from the linux nodes.

Windows hosts are -

Major    : 10
Minor    : 0
Release  : 1809
Build    : 17763
Revision : 1339

**Comment by mfuentes-newrelic** [comment]
Hi @jayntguru !
I am sorry for the late reply! We are currently testing the latest changes on the integration for Windows nodes. We will give you an update as soon as possible.

**Comment by jfjoly** [comment]
No update on this yet. We have not forgotten about this issue.

**Comment by davidbrota** [comment]
Hi @jayntguru,

We released a new Kubernetes version for Windows ([v2.2.0](https://hub.docker.com/r/newrelic/infrastructure-k8s/tags?page=1&ordering=last_updated&name=2.2.0-windows)). You could try to update to that version and see if it solves the issue. Unfortunately, we no longer offer support for Kubernetes on Windows. 

However, we have provided [build instructions](https://github.com/newrelic/nri-kubernetes/blob/main/WINDOWS.md) in case someone wants to build the image themselves.
