### ISSUE TITLE
Need to pull resourcequota metrics from KSM 

### ISSUE THREAD

**Issue by qyang-newrelic** [newrelic/nri-kubernetes#121]
## Is your feature request related to a problem? Please describe.
No

## Feature Description
Need to get resource quota metrics data from KSM.  This is useful for ops team to monitor the resource usage compared to the limit that is enforced. 

## Describe Alternatives
Will need to use Prometheus and then export  to NR . 

## Priority
Really Want

**Comment by qyang-newrelic** [comment]
KSM Resource Quota Metrics: 
https://github.com/kubernetes/kube-state-metrics/blob/master/docs/resourcequota-metrics.md

**Comment by gsanchezgavier** [comment]
Hi @qyang-newrelic , the integrations is already [reporting](https://docs.newrelic.com/docs/integrations/kubernetes-integration/understand-use-data/find-use-your-kubernetes-data/) some metrics related to resources usage. Which are the resources you are particular interested into?

**Comment by qyang-newrelic** [comment]
I am looking for the metrics resourcequota by namespace. Currently the integration only report the resource usage on container/pod and node level.  This is what metrics looks like :

[mkadmin@cs19 ~]$ kubectl describe quota --namespace=newrelic
Name:            compute-resources
Namespace:       newrelic
Resource         Used  Hard
--------         ----  ----
limits.cpu       0     2
limits.memory    0     2Gi
requests.cpu     0     1
requests.memory  0     1Gi

**Comment by roobre** [comment]
This seems like an interesting addition to our list of metrics. I'll put it in the backlog so we can explore and prioritize accordingly. Thanks!

**Comment by danielgblanco** [comment]
Linking https://github.com/newrelic/nri-kubernetes/issues/597 here
