### ISSUE TITLE
k8s-stg/night: Automate nightly builds for nri-kubernetes

### ISSUE THREAD

**Issue by roobre** [newrelic/nri-kubernetes#125]
We should automate the generation of nightly builds for nri-kubernetes.
These builds should include:
* The latest pre-release of nri-kubernetes
* The latest pre-release of all of the integrations that are present in the bundle

In order to achieve this, we can follow two approaches:
1. Implement nightly builds on nri-kubernetes repo, using `newrelic/infrastructure-bundle-nightly` as a base
2. Deprecate `infrastructure-k8s` and bundle nri-kubernetes in the infrastructure bundle, thus reusing the logic already present there

**Comment by invidian** [comment]
>Deprecate infrastructure-k8s and bundle nri-kubernetes in the infrastructure bundle, thus reusing the logic already present there

I'm not sure about the deadline, but this option seems _much_ more reasonable than the first one.

**Comment by roobre** [comment]
This was my personal favorite as well :)

However there are some extra challenges in there, as we'd need to:

1. Change all the helm charts to point to the new image
2. Migrate the nri-kubernetes config to v4, pe-enable it, and devise a "conditional activation" mechanism. This is a feature of the agent that ensures that the integration only runs when certain conditions are met. Typically an env var is used.
3. Incorporate the "unprivileged" logic, or a similar thing, into the `infrastrcuture-bundle` Dockerfile. Not impossible either but a bit convoluted.
4. Modify the `infrastrcuture-bundle` so they release the unprivileged images.

I think this is all doable in reasonable time but would require a bit more time than copypasting a pipeline.

**Comment by invidian** [comment]
Hmm, thanks for more details @roobre. Given that copying the pipeline is not really copying, but just having something similar, I think it will be easier to indeed have a separate pipeline for nightlies here for now and we can do architectural improvements at it's own pace.

I created https://github.com/newrelic/nri-kubernetes/pull/134 to address this issue. I think your comment should be converted enhancement issue then.
