### ISSUE TITLE
Add support for node condition metrics from KSM

### ISSUE THREAD

**Issue by paologallinaharbur** [newrelic/nri-kubernetes#138]
We can scrape these from KSM.

Notice that the list can vary among vendors and since the list may vary in time we could be forced to fetch everything and create metrics like "condition.abc=value"

Notice that value can be either true, false or unknown. We can stick with those or move it to numerical values as 0/1/2

Since we are collapsing 3 prometheus metrics into 1, deal with possible conflicts due to wrong data input

**Comment by invidian** [comment]
>	Deal with wrong data reported (true and false at the same time)

We should check whether it is even possible to have the same condition in Node object, with 2 contradicting values.

**Comment by invidian** [comment]
>We should check whether it is even possible to have the same condition in Node object, with 2 contradicting values.

I've checked that and it seems Node Problem Detector just overrides previous condition of given type? with the next value, without any special care. I couldn't also find and specific details about handling of duplicate conditions in the API itself.

And while doing manual tests, my custom conditions were getting removed from Node object very quickly, so I wasn't able to test that either. I don't think this is something we should care about too much.
