### ISSUE TITLE
Inconsistent Errors in Different Environments

### ISSUE THREAD

**Issue by andrewpurdin** [newrelic/nri-kubernetes#14]
Hello,

We are running the limited release New Relic Kubernetes integration for Windows on our EKS clusters in AWS across several environments.

## Description

In several of our environments it works cleanly. In another environment, on one cluster in a given account it seems to work on one of the two Windows nodes but not the other. On another cluster in the same new relic account and environment, it seems to not work on any of the 5 Windows nodes.

## Steps to Reproduce

Simply deploy the daemonset

## Expected Behavior

No error messages or failures.

## Relevant Logs / Console output

When the integration fails we receive these errors consistently:

ime="2020-08-07T10:46:41-07:00" level=error msg="Integration command failed" error="exit status 1" instance=nri-kubernetes integration=com.newrelic.kubernetes prefix=integration/com.newr │
│ elic.kubernetes stderr="time=\"2020-08-07T10:46:31-07:00\" level=warning msg=\"Cache file (c:\\\\var\\\\cache\\\\nr-kubernetes\\\\infra-sdk-cache.json) is older than 1m0s, skipping loading from disk.\"\ │
│ ntime=\"2020-08-07T10:46:41-07:00\" level=panic msg=\"No data was populated\"\ntime=\"2020-08-07T10:46:41-07:00\" level=fatal msg=\"No data was populated\"\n" working-dir="C:\\Program Files\\New Relic\\ │
│ newrelic-infra\\newrelic-integrations"

## Your Environment

Running Kubernetes 1.16 on EKS.

## Additional context

We would like to troubleshoot the issue and narrow down how we can address it. 

Thanks!

**Comment by andrewpurdin** [comment]
Update: I've narrowed the problem a bit. On the nodes where the integration is failing, running the integration from the pod produces this result consistently: 
```
C:\Program Files\New Relic\newrelic-infra\newrelic-integrations\bin>nri-kubernetes.exe -verbose
WARN[0000] Cache file (c:\var\cache\nr-kubernetes\infra-sdk-cache.json) is older than 1m0s, skipping loading from disk.
DEBU[0000] Integration "com.newrelic.kubernetes" with version 1.21.0 started
DEBU[0000] Found cached copy of "kubelet-client" stored at 2020-08-10 00:37:42 -0700 PDT
DEBU[0000] Kubelet node IP = 10.210.160.76
DEBU[0000] Discovering KSM using DNS / k8s ApiServer (default)
DEBU[0000] Found cached copy of "ksm-client" stored at 2020-08-09 23:38:37 -0700 PDT
DEBU[0000] KSM Node = 10.210.160.226
DEBU[0000] Running job: kubelet
DEBU[0000] Calling Kubelet endpoint: https://10.210.160.76:10250/pods
DEBU[0000] Calling Kubelet endpoint: https://10.210.160.76:10250/metrics/cadvisor
DEBU[0000] Calling Kubelet endpoint: https://10.210.160.76:10250/stats/summary
DEBU[0005] Calling Kubelet endpoint: https://10.210.160.76:10250/stats/summary
DEBU[0010] Job kubelet took 10.059s
DEBU[0010] populate errors:, error querying Kubelet. Get "https://10.210.160.76:10250/stats/summary": context deadline exceeded (Client.Timeout exceeded while awaiting headers)  datasource=k
ubelet phase=populate
PANI[0010] No data was populated
DEBU[0010] Integration "com.newrelic.kubernetes" exited
FATA[0010] No data was populated
```
So it seems like it can't query the kubelet for the node info at /stats/summary. 

The helm chart is virtually the same in all environments, and in one environment one windows node is failing while the other is succeeding (which to me rules out RBAC issues and the like). This remained the case even after replacing both nodes.

**Comment by jfjoly** [comment]
Hey @andrewpurdin, thanks for filing this bug report, Reporter! We’ll be looking at it more in depth soon.

**Comment by andrewpurdin** [comment]
Hey there, good news, we upgraded to the latest Windows EKS optimized AMI and went to K8s 1.17 in our cluster and some combination of those changes seems to have resolved this issue. The problem may have been related to https://github.com/aws/containers-roadmap/issues/988, which I expect to close based on this AMI release.

**Comment by jfjoly** [comment]
Great news! Thanks for the update @andrewpurdin
