### ISSUE TITLE
HPA metrics renaming on KSM 2.0.0

### ISSUE THREAD

**Issue by gsanchezgavier** [newrelic/nri-kubernetes#147]
## Is your feature request related to a problem? Please describe.
version v2.0.0 of KSM [introduces](https://github.com/kubernetes/kube-state-metrics/commit/eb01334f2d03ebc3ab25cd7b29d0ff28f6ca5ee0#diff-188b61ae111e0aff2d8d304269c6eda2f028ee4d46c0e7dabbfea4a1370698a1) a metric name renaming for HPA.

## Feature Description
Add support for this new metrics names for the HPA Sample

**Comment by invidian** [comment]
This metrics are renamed since v2.0.0.

**Comment by pzimno** [comment]
Given KSM 1.9.8 is pretty outdated according to the [compatibility matrix ](https://github.com/kubernetes/kube-state-metrics#compatibility-matrix) will KSM 2.x support be available anytime soon so HPA metric will work with newrelic-infra?

**Comment by maverickCoastCode** [comment]
I guess due to renaming of hpa metrics from KSM v2.0.0, HPA metrics has  stopped reporting since we update to KSM v2.3.0 from v1.9.8. any leads on the solution?

**Comment by gsanchezgavier** [comment]
Hi @maverickCoastCode the integration [currently](https://docs.newrelic.com/docs/kubernetes-pixie/kubernetes-integration/get-started/kubernetes-integration-compatibility-requirements#requirements) supports KSM 1.9.8 .
We plan to support more recent versions but there is not a date yet.

**Comment by ivan-santos-eq** [comment]
Howdy! It has been a while since this ticket was created. Any progress on 2.x support?

**Comment by marcsanmi** [comment]
Closing this as support for KSM v2 was already [released](https://github.com/newrelic/helm-charts/releases/tag/nri-bundle-5.0.0).
