### ISSUE TITLE
Verify toUtilization() use

### ISSUE THREAD

**Issue by invidian** [newrelic/nri-kubernetes#152]
`toUtilization()` function right now use `definition.FromRaw` for getting values for calculation, however, e.g. `processFdsUtilization` metric use `processOpenFds` and `processMaxFds` metrics as argument for `toUtilization()` , which come from prometheus metrics and as far as I understand, won't be available for `definition.FromRaw`, as computed metrics are stored in `metric.MetricSet` type, which only allows adding metrics, not reading from them.

I suspect that `toUtilization()` might also be mis-used for other metrics. It should be verified.

**Comment by paologallinaharbur** [comment]
Superseeded by https://github.com/newrelic/nri-kubernetes/issues/311 and fixed
