### ISSUE TITLE
Discovery cache works only for single URI

### ISSUE THREAD

**Issue by invidian** [newrelic/nri-kubernetes#164]
See https://github.com/newrelic/nri-kubernetes/blob/c328361e5b92371950212e39cdd5b48e0dcc37a7/src/client/cached.go#L94-L110

If the URI is not cached, discovery is being re-triggered and cache is being discarded, this seems like a very inefficient way of caching.

**Comment by invidian** [comment]
So this sort of cache make sense for KSM as it only has a single URI, but doesn't make much sense for kubelet, as they are at least few endpoints which will always be queried.

**Comment by paologallinaharbur** [comment]
closing. No cache is leveraged in new solution
