### ISSUE TITLE
PID 1 should be newrelic-infra-service

### ISSUE THREAD

**Issue by varas** [newrelic/nri-kubernetes#22]
# PID 1 should be newrelic-infra-service

## Description

You are also overriding base image CMD `/usr/bin/newrelic-infra-service` with `/usr/bin/newrelic-infra`. 

This might lead to unexpected behaviour like broken shutdown cause report or hot config reload misbehaviour.

## Expected Behavior

Tini should be the entrypoint (see https://github.com/newrelic/nri-kubernetes/pull/21) and then CMD `/usr/bin/newrelic-infra-service` should run right after.

**Comment by jorik** [comment]
This has been fixed in #23
