### ISSUE TITLE
Update docs, Readme and remove references to old architecture

### ISSUE THREAD

**Issue by paologallinaharbur** [newrelic/nri-kubernetes#226]
The whole solution changed a Lot and we will need To update docs accordingly.
 - We will need to review all the pages checking and fixing incongruences.
Keep in mind that people will still use old architecture for a while, therefore we should place warnings and disclaimer to warn them 

 - Notice that also charts, integrations readme needs to be updated as well.
 - We should provide an example of how configure integration with new arch

**Comment by roobre** [comment]
Docs PR: https://github.com/newrelic/docs-website/pull/5715
