### ISSUE TITLE
HTTPS client does not respect global timeouts

### ISSUE THREAD

**Issue by invidian** [newrelic/nri-kubernetes#237]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description
[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT share sensitive information, whether personal, proprietary, or otherwise! )

Given timeout as argument is not used anywhere:

https://github.com/newrelic/nri-kubernetes/blob/67ede685d0ee0f5be00ec903c0a1806f03304d5d/src/client/client.go#L92-L98

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen. )

HTTPS requests follow the same semantics as HTTP calls, respecting global request timeout.

## Additional context
[TIP]:  # ( Add any other context about the problem here. For example, relevant community posts or support tickets. )

Found while working on #217

**Comment by paologallinaharbur** [comment]
All clients are now using pester having their own timeout
