### ISSUE TITLE
Support generic authentication beyond bearer token

### ISSUE THREAD

**Issue by invidian** [newrelic/nri-kubernetes#238]
## Is your feature request related to a problem? Please describe.

Right now, scraping metrics does not work when client certificates are used instead of bearer token in given kubeconfig.

## Feature Description

To simplify code, supporting generic authentication mechanisms from kubeconfig would be preferred.

## Additional context

Found while working on #217 

## Priority
Please help us better understand this feature request by choosing a priority from the following options: 
[Nice to Have, Really Want, Must Have, Blocker] 
Nice to Have

**Comment by paologallinaharbur** [comment]
Kubeconfig has been added as well as transportFor, this will work however only leveraging connection through proxy
