### ISSUE TITLE
Clean up ways of handling bearer tokens

### ISSUE THREAD

**Issue by invidian** [newrelic/nri-kubernetes#239]
## Is your feature request related to a problem? Please describe.

Right now, the following code is used to create authenticated HTTP clients:
https://github.com/newrelic/nri-kubernetes/blob/67ede685d0ee0f5be00ec903c0a1806f03304d5d/src/ksm/client/discovery.go#L139-L143
https://github.com/newrelic/nri-kubernetes/blob/67ede685d0ee0f5be00ec903c0a1806f03304d5d/src/kubelet/client/discovery.go#L93-L95
https://github.com/newrelic/nri-kubernetes/blob/67ede685d0ee0f5be00ec903c0a1806f03304d5d/src/controlplane/client/discovery.go#L131-L132

## Feature Description

It would be good to unify this code to use https://pkg.go.dev/k8s.io/client-go/rest#TransportFor, which would also solve #238.

## Additional context

Found while working on #217 

## Priority
Please help us better understand this feature request by choosing a priority from the following options: 
[Nice to Have, Really Want, Must Have, Blocker] 
Nice to Have

**Comment by paologallinaharbur** [comment]
I tried it, however I carry on facing the following when connecting to kubelet:
```
14:33:45.389666 [DEBUG] Kubelet connection with nodeIP failed: no connection succeeded through localhost: error trying to connect to: https://192.168.183.33:10250/healthz. Got error: Get "https://192.168.183.33:10250/healthz": x509: cannot validate certificate for 192.168.183.33 because it doesn't contain any IP SANs
```

The certificate in the kubeconfig is of the ApiServer and it cannot be used to authenticate against kubelet (at least in minikube)

Adding a Skip verify `inClusterConfig.TLSClientConfig.Insecure = true` (that was already present) we noticed a weird behaviour 

```
14:29:02.879227 [DEBUG] trying connecting to kubelet directly with nodeIP
14:29:02.900059 [DEBUG] Kubelet connection with nodeIP failed: no connection succeeded through localhost: error trying to connect to: https://192.168.183.33:10250/healthz. Got error: Get "https://192.168.183.33:10250/healthz": x509: cannot validate certificate for 192.168.183.33 because it doesn't contain any IP SANs
14:29:02.900392 [DEBUG] trying connecting to kubelet directly with API proxy
[ERR] building Kubelet client: connecting to kubelet: connection failed both locally and with API server: testing connection through API: error trying to connect to: https://10.96.0.1:443/api/v1/nodes/minikube/proxy/healthz. Got error: Get "https://10.96.0.1:443/api/v1/nodes/minikube/proxy/healthz": x509: certificate signed by unknown authority
```

Kubelet fails as expected, api-server shows a weird behaviour
