### ISSUE TITLE
Make discoverer easier to test

### ISSUE THREAD

**Issue by invidian** [newrelic/nri-kubernetes#241]
At the moment `Discoverer` interface https://github.com/newrelic/nri-kubernetes/blob/0a78aa518374cc8d250122d26268ba5e1858a754/src/client/discovery.go#L8-L11 returns an `HTTPClient` interface https://github.com/newrelic/nri-kubernetes/blob/0a78aa518374cc8d250122d26268ba5e1858a754/src/client/discovery.go#L20-L24 which makes it difficult to test, as it is obfuscated where the request will be sent.

Most likely we should decompose `Discoverer` interface to make it have an endpoint discovery part and client configuration part, so we can only test discovered endpoints without caring about client configuration and performing the requests.

**Comment by paologallinaharbur** [comment]
fixed dy https://github.com/newrelic/nri-kubernetes/pull/294
