### ISSUE TITLE
Add e2e tests for supported platforms/scenarios

### ISSUE THREAD

**Issue by invidian** [newrelic/nri-kubernetes#251]
As part of re-arch work, it would be nice to add some extra e2e tests, so we can test magic code like https://github.com/newrelic/nri-kubernetes/blob/e0a70cbcbc5513a66329af8e00ad3c49d6469806/src/controlplane/components.go#L124-L194 and to test scenarios like external control plane, multiple KSMs etc.

**Comment by gsanchezgavier** [comment]
As part of the control plane refactor on v3,  this hardcoded labels were moved to configuration and test were added for [auto-discovered](https://github.com/newrelic/nri-kubernetes/blob/main/src/controlplane/controlplane_test.go#L43)  components and [external](https://github.com/newrelic/nri-kubernetes/blob/main/src/controlplane/controlplane_test.go#L179) control plane scenarios as well
