### ISSUE TITLE
Add missing node net.rxBytesPerSecond and net.txBytesPerSecond to docs

### ISSUE THREAD

**Issue by carlossscastro** [newrelic/nri-kubernetes#255]
We are missing net.rxBytesPerSecond, net.txBytesPerSecond from node sample data in our documentation:

https://docs.newrelic.com/docs/kubernetes-pixie/kubernetes-integration/understand-use-data/find-use-your-kubernetes-data/#metrics

https://github.com/newrelic/nri-kubernetes/blob/2bd966fad87176a64f5601a8c55b6bd341bac2da/src/metric/definition.go#L958-L959

**Comment by paologallinaharbur** [comment]
fixed
