### ISSUE TITLE
Improve how multiple KSM instances are handled

### ISSUE THREAD

**Issue by roobre** [newrelic/nri-kubernetes#266]
## Is your feature request related to a problem? Please describe.

When multiple KSM instances are deployed in the cluster (matching the same label), autodiscovery will pick one arbitrarily. Since we use the default label KSM is deployed with, this can lead to situations where an incompatible version, already deployed in the cluster, is chosen over our compatible, bundled version.

## Feature Description
It would be nice to avoid this scenario from happening, without making users change the config just because they have deployed something else in the cluster.

## Describe Alternatives
We could:
- Instruct the user to specify a static endpoint.
- Instruct the user to change the label we search for in both the KSM subchart and ours if a second deployment is there.
- Allow to scope discovery by namespace, and possibly do that by default
- Change the label we deploy KSM with and the one we look for so it doesn't conflict with upstream ksm's

**Comment by paologallinaharbur** [comment]
Moreover it is not currently possible to change the label selector for KSM, we should expose that:

```	
dc := discovery.EndpointsDiscoveryConfig{
		LabelSelector: defaultLabelSelector,
		Client:        s.K8s,
	}
```
