### ISSUE TITLE
[chart] Control plane pods cannot be reconfigured/upgraded

### ISSUE THREAD

**Issue by kang-makes** [newrelic/nri-kubernetes#356]
## Description
ControlPlane cannot be upgraded because it fails to bind ports:
```
NAMESPACE            NAME                                                 READY   STATUS             RESTARTS   AGE
newrelic             nri-bundle-nrk8s-controlplane-c4c6dfb5-s9c55         0/2     Pending            0          73m
```
```
Events:
  Type     Reason            Age                  From               Message
  ----     ------            ----                 ----               -------
  Warning  FailedScheduling  105s (x72 over 71m)  default-scheduler  0/1 nodes are available: 1 node(s) didn't have free ports for the requested pod ports.
```

## Steps to Reproduce
Upgrade the version or change de configuration and it could not restart.

**Comment by paologallinaharbur** [comment]
This is really annoying, possible fix I see are:
 - Generating random ports with helm. 
 - modifying the daemonset.spec.updateStrategy
 - use socket to communicate
 
 By the way I tested it with minikube and daemonSet. When adding a new variable the pod was correctly deleted and recreated. Can you share more data regarding the configuration? @kang-makes

**Comment by paologallinaharbur** [comment]
After talking offline, it "fails" whenever it is deployment and you have one node only and hostnetwork is true

So, to summarize:
 - DaemonSet is fine with updateStrategy.type: RollingUpdate
 - For Deployments we'd need to change it to strategy.type: Recreate?

**Comment by paologallinaharbur** [comment]
Moreover, if it is kind=deployment we should be able to drop hostNetwork. No use-case should need that

**Comment by kang-makes** [comment]
We had a internal conversation here to have all the contexts on Paolo's notes on this issue: https://newrelic.slack.com/archives/C01516RVD4H/p1643902955055849

This issue seems scarier that it is and we can release without issues.

This issue should also be moved to `helm-charts` repository because it is there where we should fix it.

**Comment by paologallinaharbur** [comment]
@kang-makes can you update this with latest news?
