### ISSUE TITLE
Add `restartCountDelta` metric

### ISSUE THREAD

**Issue by roobre** [newrelic/nri-kubernetes#379]
## Is your feature request related to a problem? Please describe.

Right now, we report pod restarts as a cumulative number:
https://github.com/newrelic/nri-kubernetes/blob/ac95cda44565da012f15ef9249de5089e35a9406/src/metric/definition.go#L938-L938

However, the NR platform traditionally has some problems to work with cumulative counters, and detecting if a pod has been "restarted recently" becomes hard to do with a cumulative metrics.

## Feature Description

It would be nice to have a delta version of the metric, where on each report interval the integration automatically reports the difference in number of restarts w.r.t. the previous interval. This functionality is already built in the SDK and should be enough to add a metric with the `sdkMetric.PDELTA` type.

---
- [x] add new metric in nri-kubernetes
- [x] (internal link) [spec-files PR](https://source.datanerd.us/infrastructure/infra-integration-specs/pull/289) merged
- [x] (internal link) [dirac PR](https://source.datanerd.us/dirac/dirac/pull/6876) merged
- [x] create [issue to include mappings in infra-metrics-utils repo](https://github.com/newrelic/newrelic-coreint/issues/311).

**Comment by sigilioso** [comment]
[infra-integration-spects PR](https://source.datanerd.us/infrastructure/infra-integration-specs/pull/289) created

**Comment by sigilioso** [comment]
[dirac PR](https://source.datanerd.us/dirac/dirac/pull/6876) created

**Comment by sigilioso** [comment]
[Jira](https://newrelic.atlassian.net/browse/NRDB-3912) to review dirac PR after pinging #tdp-help

**Comment by davidgit** [comment]
I'm closing the issue because the dirac pr has been merged
