### ISSUE TITLE
Add livenessProbe and readinessProbe to pod definitions

### ISSUE THREAD

**Issue by maxlemieux** [newrelic/nri-kubernetes#385]
## Is your feature request related to a problem? Please describe.
When using Gatekeeper with constraints which require liveness probes and readiness probes (mentioned as a best practice in e.g. https://itnext.io/running-gatekeeper-in-kubernetes-and-writing-policies-part-1-fcc83eba93e3) the infra agent daemonset (and probably others) are not able to be installed, because they don't have these probes.

## Feature Description
Add `livenessProbe` and `readinessProbe` definitions to all pod definitions.

## Describe Alternatives
In Gatekeeper, configuring exemptions for the probe-related constraints, for the New Relic namespace, as described here: https://open-policy-agent.github.io/gatekeeper/website/docs/exempt-namespaces/

## Additional context
Reproduction (in an environment with Gatekeeper constraints requiring the probes)

```
helm upgrade --install newrelic newrelic/nri-bundle --namespace newrelic -f values.yaml --devel
Error: UPGRADE FAILED: failed to create resource: admission webhook "[validation.gatekeeper.sh](https://validation.gatekeeper.sh/)" denied the request: [liveness-probe] Rejecting "DaemonSet/newrelic-nrk8s-controlplane" for not specifying a livenessProbe
[liveness-probe] Rejecting "DaemonSet/newrelic-nrk8s-controlplane" for not specifying a livenessProbe
[readiness-probe] Rejecting "DaemonSet/newrelic-nrk8s-controlplane" for not specifying a readinessProbe
[readiness-probe] Rejecting "DaemonSet/newrelic-nrk8s-controlplane" for not specifying a readinessProbe
```

## Priority
Please help us better understand this feature request by choosing a priority from the following options: 
[Really Want]

**Comment by davidgit** [comment]
Hi @maxlemieux ,

This is not a priority right now but still, we'd encourage you to open a FR through the official channel (_Aha_).

Thanks!
