### ISSUE TITLE
Integration version

### ISSUE THREAD

**Issue by paologallinaharbur** [newrelic/nri-kubernetes#392]
Integration version is now reported as vx.x.x
Other integration reports it as x.x.x

**Comment by kang-makes** [comment]
I see all the other integrations tagged (in repos) as `vx.y.z` and the tag from the repository is used to version de integration itself.

Where are you seeing this issue?

**Comment by paologallinaharbur** [comment]
In the data reported in newrelic (if I remember it correctly)
