### ISSUE TITLE
Control plane "metric attributes exceeds 240 limit, some might be lost"

### ISSUE THREAD

**Issue by paologallinaharbur** [newrelic/nri-kubernetes#397]
The agent limits the number of attributes to 240 for several reasons.

Our integration was not enforcing this limit, but most of the samples have a fixed number of attributes unless the users attaches hundreds of labels or custom attributes.

Unfortunately some samples gather metrics from prometheus  automatically transforming them into attributes. If cardinality of the dimensions is too big we would overcome the 240 limit and the sample is dropped entirely.

```
apiserverRequestDelta_verb_VERB_code_CODE | Difference of the number of apiserver requests, broken out for each verb and HTTP response code
-- | --
apiserverRequestRate_verb_VERB_code_CODE | Rate of apiserver requests, broken out for each verb and HTTP response code
restClientRequestsDelta_code_CODE_method_METHOD | Difference of the number of HTTP requests, partitioned by method and code
restClientRequestsRate_code_CODE_method_METHOD | Rate of the number of HTTP requests, partitioned by method and code
etcdObjectCounts_resource_RESOURCE-KIND
```

---

In particular a user sent us a payload affected by this issue and the "exploding" dimensions are:
 - etcdObjectCounts in particular with many CRD
 - apiserverRequestsDelta
 - apiserverRequestsRate

---

In big cluster we could do some of the following:
 - split samples if the #attributes>240
 - give the possibility to user to filter any of the metrics (this could helm in different scenarios)
 - avoid reporting metrics for any code+method have a 0 rate -> risk to confuse missing data with 0
 
 
 [blocker for apiServer monitoring in large cluster ]

**Comment by daboom** [comment]
Hey guys, are there any news on this or any tests I can do on the cluster we're trying to get metrics from?

**Comment by daboom** [comment]
> Hey guys, are there any news on this or any tests I can do on the cluster we're trying to get metrics from?
any news?
