### ISSUE TITLE
Question: Windows support in version 3.x

### ISSUE THREAD

**Issue by evegaval** [newrelic/nri-kubernetes#430]
## Is your feature request related to a problem? Please describe.
Version 2.x used to support the installation on Windows k8s clusters, since Version 3.x it seems this support has been dropped and Version 2.x is deprecated now.

## Feature Description
will Windows installation be supported in Version 3.x ?

## Describe Alternatives
-

## Additional context
Current error message returned when installing version 3
```
nri-kubernetes v3 does not support deploying into windows Nodes.
Please use the latest 2.x version of the chart.
```

## Priority
Please help us better understand this feature request by choosing a priority from the following options: 
Nice to Have

**Comment by mangulonr** [comment]
Hi @evegaval

**Comment by mangulonr** [comment]
Hi @evegaval

**Comment by mangulonr** [comment]
Hi @evegaval

**Comment by evegaval** [comment]
Hi @mangulonr  thanks for the response. Regarding the alpha K8s windows integration, is this completely deprecated, meaning that no more work will be done on it for example bug fixes ?

**Comment by mangulonr** [comment]
Hi @evegaval

Do you have any other question?
Can we close the issue?
