### ISSUE TITLE
Refresh Kubernetes service account token

### ISSUE THREAD

**Issue by sdickhoven** [newrelic/nri-kubernetes#434]
## Description

> Hello,
> 
> We have identified applications running in one or more of your Amazon EKS clusters that are not refreshing service account tokens. Applications making requests to Kubernetes API server with expired tokens will fail. You can resolve the issue by updating your application and its dependencies to use newer versions of Kubernetes client SDK that automatically refreshes the tokens. 
> 
> What is the problem?
> 
> Kubernetes version 1.21 graduated BoundServiceAccountTokenVolume feature to beta and enabled it by default. This feature improves security of service account tokens by requiring a one hour expiry time, over the previous default of no expiration. This means that applications that do not refetch service account tokens periodically will receive an HTTP 401 unauthorized error response on requests to Kubernetes API server with expired tokens. You can learn more about the BoundServiceAccountToken feature in EKS Kubernetes 1.21 release notes.
> 
> To enable a smooth migration of applications to the newer time-bound service account tokens, EKS v1.21+ extends the lifetime of service account tokens to 90 days. Applications on EKS v1.21+ clusters that make API server requests with tokens that are older than 90 days will receive an HTTP 401 unauthorized  error response.
> 
> How can you resolve the issue?
> 
> To make the transition to time bound service account tokens easier, Kubernetes has updated the below official versions of client SDKs to automatically refetch tokens before the one hour expiration:
> 
> * Go v0.15.7 and later
> * Python v12.0.0 and later
> * Java v9.0.0 and later
> * Javascript v0.10.3 and later
> * Ruby master branch
> * Haskell v0.3.0.0
> 
> We recommend that you update your application and its dependencies to use one of the above client SDK versions if you are on an older version. 
> 
> As of April 20th 2022, we have identified the below service accounts attached to pods in one or more of your EKS clusters using stale (older than 1 hour) tokens. Service accounts are listed in the format : &lt;eks-cluster-arn&gt;|&lt;namespace:serviceaccount&gt;
> 
> &lt;redacted&gt;|kube-system:newrelic-logging
> &lt;redacted&gt;|kube-system:newrelic-infrastructure-nrk8s-controlplane

## Expected Behavior

For managed Kubernetes clusters, the `newrelic-infrastructure-nrk8s-controlplane` component (`Deployment`, not `DaemonSet` with control plane node affinity) interrogates the Kubernetes API via `https://kubernetes.default:443` (rather than unauthenticated(?) via `localhost`).

In order to do this successfully, it must use the service account token stored at `/var/run/secrets/kubernetes.io/serviceaccount/token`.

According to our kube audit log, the service account token is **not** refreshed periodically as it should be.

I would expect the `newrelic-infrastructure-nrk8s-controlplane` component to reread the service account token whenever it is updated and/or before a certain amount of time (possibly configurable) elapses.

⚠️ Note: Filesystem events (`inotify`) are best effort and should therefore not be relied upon exclusively.

## [Troubleshooting](https://discuss.newrelic.com/t/troubleshooting-frameworks/108787) or [NR Diag](https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/troubleshooting/new-relic-diagnostics) results

N/A

## Steps to Reproduce

Perform the following CloudWatch Logs Insights query for the kube audit log:

```
fields @timestamp
| filter @logStream like /kube-apiserver-audit-/
| filter @message like /seconds after warning threshold/
| parse @message "subject: *, seconds after warning threshold:*\"" as subject, elapsedtime
| filter subject like /newrelic-infrastructure/
```

...or equivalent log query wherever your kube audit log goes if you operate the control plane yourself.

## Your Environment

AWS EKS (managed Kubernetes), version 1.21
[NRI Helm Chart](https://github.com/newrelic/nri-kubernetes/tree/newrelic-infrastructure-3.3.6/charts/newrelic-infrastructure), version 3.3.6

```
$ kubectl get deploy -n kube-system newrelic-infrastructure-nrk8s-controlplane -o jsonpath="{.spec.template.spec.containers[0].image}"
newrelic/nri-kubernetes:3.1.0
```

☝️ the `Chart.yaml` claims that the `appVersion` is [3.1.1](https://github.com/newrelic/nri-kubernetes/blob/newrelic-infrastructure-3.3.6/charts/newrelic-infrastructure/Chart.yaml#L12) so that seems to be a bug.

## Additional context
Same issue: https://github.com/newrelic/newrelic-fluent-bit-output/issues/110

**Comment by sdickhoven** [comment]
according to amazon's message (specifically: "use go library v0.15.7 and later"), this issue can probably be closed actually.

see: https://github.com/newrelic/nri-kubernetes/blob/v3.1.0/go.mod#L19

i've been trying to understand the client-go code to see how exactly it works. i know that for the "auth exec" logic the client library only refreshes the token when it receives a `401` from the kubernetes api.

since amazon is allowing the "expired" token to keep working for 90d it's possible that the "using expired token" messages are really a red herring and that everything will work as expected as soon as the kubernetes api actually refuses access. 🤷

**Comment by alvarocabanas** [comment]
Yes, we are not aware of any problem with expired tokens and as you point out, our version of the go client is v1.22, so we are way above the minimum required Go v0.15.7

**Comment by gugacavalieri** [comment]
I am also seeing stale token logs when using the Infrastructure Agent with EKS-Fargate. How can we be sure that the `go-client` will automatically refresh the token when it gets a 404?

Using the Helm Charts to Deploy.
nri-bundle Version: `4.7.0`

Sidecar container on Fargate: 

```
│   newrelic-infrastructure-sidecar:                                                                                                                                                                                │
│     Container ID:   containerd://1248c734dbf181922907c9ed3a61873ca706eaa220bbd1003a4cc3127bda30aa                                                                                                                 │
│     Image:          newrelic/infrastructure-k8s:2.10.0-unprivileged                                                                                                                                               │
│     Image ID:       docker.io/newrelic/infrastructure-k8s@sha256:6ade79e1627f5987bd85d49a388a20bfee20d17a6a6ba5e500842df14659097c                                                                                 │
│     Port:           <none>                                                                                                                                                                                        │
│     Host Port:      <none>                                                                                                                                                                                        │
│     State:          Running
```

**Comment by kang-makes** [comment]
Hi @gugacavalieri,

Our integration with Fargate should not have that issue because our integration works differently in that kind of environments. Fargate is still using the v2 of our Kubernetes integration, the agent is a sidecar bundled with the kubernetes integration and it runs one shot (like all our other integrations) every 15 seconds.

The client of Kubernetes' API Server is created and destroyed every 15 seconds so the token should rotate: https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.21.md

> The BoundServiceAccountTokenVolume feature has been promoted to beta, and enabled by default.
>
>    Clients should reload the token from disk periodically (once per minute is recommended) to ensure they continue to use a valid token. k8s.io/client-go version v11.0.0+ and v0.15.0+ reload tokens automatically.

We see no way to create an environment where we can reproduce your issue so we are keeping this ticket closed.

Best regards

**Comment by gugacavalieri** [comment]
Thanks @kang-makes!

Yeah, it's weird that we are seeing this warnings on the Kube API logs.

From my research I can confirm that :
* EKS 1.21 is generating JWT tokens with 1 year of `exp`.
* Although this tokens expire in 1 year, they get rotated every 30-60 min
* **NewRelic side car is refreshing the tokens between 30-60 min (The logs always show that the token is getting refreshed under 1 hour)**

Don't know why we are seeing the warnings in the Kube API but it appears that everything is being refreshed under 1 hour, so it should be good!
