### ISSUE TITLE
Nodes `fullHostname` appears as a service name if any service is bound to the host IP

### ISSUE THREAD

**Issue by roobre** [newrelic/nri-kubernetes#435]
## Description

If in the cluster there is a service having the host's IP address as an endpoint (e.g. a pod with `hostNetwork: true`), CoreDNS will return the service name as the reverse for the Host's IP, rather than forwarding this upstream.

This causes the agent to report that service name as the `fullHostname` for the node.

## Expected Behavior

`fullHostname` for the nodes should be the FQDN of the node, not a service name.

**Comment by roobre** [comment]
To be discussed with @rubenruizdegauna

**Comment by jayntguru** [comment]
Just wanted to say that we're seeing this as of V3 and it's causing some issues.

**Comment by paologallinaharbur** [comment]
This issue is fixed in the nri-kubernetes chart, but it will take some days to get propagated to nri-bundle
