### ISSUE TITLE
Check that the new solution for k8s v1.23 deploys on last versions of AWS

### ISSUE THREAD

**Issue by marcsanmi** [newrelic/nri-kubernetes#439]
As it says here https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html.
AWS won't release EKS 1.23 until August 2022.

**Comment by alvarocabanas** [comment]
As it says here https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html.
AWS won't release EKS 1.23 until August 2022. 
We have to check our canaries that are on 1.19 and update them to a newer version because June 30, 2022 will be end of support.
