### ISSUE TITLE
Review kubelet new metrics for v.1.23

### ISSUE THREAD

**Issue by marcsanmi** [newrelic/nri-kubernetes#444]
We will need to discuss which ones are worth adding, if any.

**Comment by kang-makes** [comment]
I filtered the ones marked as ALPHA. From 1.22 to 1.23 these are the new metrics exposed from API Server:
 * `apiserver_admission_controller_admission_duration_seconds`: Admission controller latency histogram in seconds, identified by name and broken out for each operation and API resource and type (validate or admit).
 * `apiserver_admission_step_admission_duration_seconds`: Admission sub-step latency histogram in seconds, broken out for each operation and API resource and step type (validate or admit).
 * `apiserver_current_inflight_requests`: Maximal number of currently used inflight request limit of this apiserver per request kind in last second.
 * `apiserver_response_sizes`: Response size distribution in bytes for each group, version, verb, resource, subresource, scope and component.

**Comment by alvarocabanas** [comment]
This is the metrics and data gathered https://docs.google.com/document/d/1nq58SdyOGk7FG8yxCF-lo9OJtjQarpVPPkHcqEaDALw/edit
