### ISSUE TITLE
doc: guide to obtain control-plane metrics in GKE

### ISSUE THREAD

**Issue by sigilioso** [newrelic/nri-kubernetes#477]
control-plane metrics are not fetched out-of-the-box in GKE. It would be useful to provide a guide to configure your cluster and the integration to obtain those metrics.

**Comment by paologallinaharbur** [comment]
where you thinking to something like [this](https://docs.newrelic.com/docs/kubernetes-pixie/kubernetes-integration/advanced-configuration/configure-control-plane-monitoring/#cloud-control-plane) or were you referring some something like a step to step guide?

**Comment by sigilioso** [comment]
I was thinking of a step to step guide, but I actually didn't find the link you provided... maybe that is enough
