### ISSUE TITLE
Check the correct version is pointed in deployment ymls before releasing

### ISSUE THREAD

**Issue by roobre** [newrelic/nri-kubernetes#53]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description
[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT share sensitive information, whether personal, proprietary, or otherwise! )

Release pipeline (#50) does not check that the version being released is the one used in deployment yamls. This can cause inconsistencies with the versioning in the S3 bucket.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen. )

A deployment named `newrelic-infrastructure-k8s-1.2.3.yml` is expected to refer to deploy version `1.2.3`.

**Comment by paologallinaharbur** [comment]
I noticed that nri-kube-events has the same issue? Can you add the same check there as well @roobre 
 (maybe other pipelines also when pushing the manifest)
