### ISSUE TITLE
Capability to extend tags to send additional data en K8s?samples tables

### ISSUE THREAD

**Issue by arturoth** [newrelic/nri-kubernetes#533]
## Is your feature request related to a problem? Please describe.
Let me time to explain our problem, In our case we define the same name of different cluster in different environments and this definition causes:
- Multiple values assigned for same cluster name but data is generate by different environments.
- When we try to get data from NRQL queries, the output are multiple values assigned to this environments.

## Feature Description
Capability to extend tags to all K8s?samples tables.

## Describe Alternatives
I cant found any alternatives for extend tags.

## Additional context
This solution help us to difference registers when cluster name are the same, indistinct if implements are on on-prem or cloud provider solutions

## Priority
Blocker, without this capability we dont have possibilities to monitoring samples.

**Comment by kang-makes** [comment]
Hi @arturoth,

Are you talking about custom attributes? https://github.com/newrelic/nri-kubernetes/blob/main/charts/newrelic-infrastructure/values.yaml#L473-L474

**Comment by arturoth** [comment]
> Hi @arturoth,
> 
> Are you talking about custom attributes? https://github.com/newrelic/nri-kubernetes/blob/main/charts/newrelic-infrastructure/values.yaml#L473-L474

Thank you very much @kang-makes ... I had overlooked that attribute. 

Sorry, I'll give it a try, much appreciated always.
