### ISSUE TITLE
Add missing metrics

### ISSUE THREAD

**Issue by jlegoff** [newrelic/nri-kubernetes#56]
A number of metrics are being computed on the fly by the backend, as explained in this document: https://docs.google.com/document/d/1C45zYn7StoJfbjqxe70rRB-bZREbg8bqwIJRooXzkX8

These computed metrics should be added by the integration.

**Comment by arvdias** [comment]
A bit more context for this Issue:

- Some metrics for this is integration are being calculated in the backend from the data we're sending. 
- These metrics are being used in "special" alerts we provide for customers. 
- While calculating them in the backend works, we should add these metrics to the integration as it makes them easier to manage in the backend and reduces the workaround currently in place.

Event type: 
- K8sReplicasetSample, 
- K8sStatefulSample, 
- K8sDeploymentSample, 
- K8sDaemonsetSample
Calculation: **podsMissing** = podsDesired - podsReady

Event type: K8sContainerSample
Calculation: **cpuCoresUtilization** = (cpuUsedCores / cpuLimitCores) * 100

Event type: K8sContainerSample
Calculation: **requestedCpuCoresUtilization** = (cpuUsedCores / cpuRequestedCores) * 100

Event type: K8sContainerSample
Calculation: **memoryUtilization** = (memoryUsedBytes / memoryLimitBytes) * 100

Event type: K8sContainerSample
Calculation: **requestedMemoryUtilization** = (memoryUsedBytes / memoryRequestedBytes) * 100

Event type: K8sEtcdSample
Calculation: **processFdsUtilization** = (processOpenFds / processMaxFds) * 100

Event type: K8sNodeSample
Calculation: **allocatableCpuCoresUtilization** = (cpuUsedCores / allocatableCpuCores) * 100

Event type: K8sNodeSample
Calculation: **allocatableMemoryUtilization** = (memoryWorkingSetBytes / allocatableMemoryBytes) * 100

Event type: K8sNodeSample
Calculation: **fsCapacityUtilization** = (fsUsedBytes / fsCapacityBytes) * 100

**Comment by arvdias** [comment]
Another set of metrics we will add as part of this issue are Horizontal Pod Autoscaler Metrics: https://github.com/kubernetes/kube-state-metrics/blob/master/docs/horizontalpodautoscaler-metrics.md
