### ISSUE TITLE
Restart count of kubelet container is too high 

### ISSUE THREAD

**Issue by achupryn** [newrelic/nri-kubernetes#579]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description
We found that on our clusters restart count of kubelet container on some of the nodes > 100 (since 3 days ago)
log error:
`time="2022-11-21T06:18:17Z" level=error msg="retrieving scraper data: retrieving kubelet data: kubelet data was not populated after trying all endpoints"
`

## Expected Behavior
-  retry to get metrics N times before restarting the kubelet container
- endpoints can be found in the error log

## Your Environment
nri-bundle version: 4.9.3
k8s version: 1.23.12 (azure aks)

**Comment by davidgit** [comment]
Hi , 

The next best step is to visit [New Relic Support](https://support.newrelic.com/), where you can engage the New Relic Support Community or open a support ticket depending on your support level. The support team is best positioned to assist with your specific needs. 

Please provide a link to this GitHub issue when submitting your community post or support ticket.

Thanks!
