### ISSUE TITLE
KSM and Kubelet scrapers set their `dnsPolicy` based on the controlPlane scraper settings

### ISSUE THREAD

**Issue by roobre** [newrelic/nri-kubernetes#590]
https://github.com/newrelic/nri-kubernetes/blob/73989d367ff6f486c86298468b9cf1252729d816/charts/newrelic-infrastructure/templates/ksm/deployment.yaml#L53-L55

https://github.com/newrelic/nri-kubernetes/blob/73989d367ff6f486c86298468b9cf1252729d816/charts/newrelic-infrastructure/templates/kubelet/daemonset.yaml#L54-L56

I think this could be a copy-paste artifact, and these templates should be checking their own's `hostNetwork` setting and not the controlplane's.

**Comment by davidgit** [comment]
NR issues: https://issues.newrelic.com/browse/NEWRELIC-5927
