### ISSUE TITLE
nri-kubernetes causes other pods to get stuck in Terminating state

### ISSUE THREAD

**Issue by nickperry** [newrelic/nri-kubernetes#593]
We are using nri-kubernetes 3.4.1. The presence of NRI on a node causes pods which were started prior to the NRI pod to hang in Terminating state when we delete them.

The Kubelet will sit logging errors like:

`kubelet[2061]: E1215 20:43:45.021535    2061 generic.go:415] "PLEG: Write status" err="rpc error: code = Unknown desc = failed to get sandbox ip: check network namespace closed: remove netns: unlinkat /var/run/netns/cni-b2a7a309-99f4-349f-26da-88063637a414: device or resource busy" pod="foo/bar"`

The affected clusters are running Kubernetes 1.24.8 with containerd and Calico 3.23.3 (using VXLAN). The underlying nodes are Oracle LInux 7. I do not believe the problem was present prior to the upgrade from Kubernetes 1.23 and removal of Docker. I have also not seen this affect our Tanzu clusters (1.22.9, Containerd, Photon, Calico).

We deploy NRI using the Helm chart.

I have confirmed that if we remove New Relic Infra, the problem is immediately fixed and the pods hanging in Terminated are cleaned up.

This is exactly the same problem as described here:

https://discuss.newrelic.com/t/pods-are-stuck-in-terminating-state-after-installation-of-kubernetes-integration/186080

**Comment by davidgit** [comment]
Hi @nickperry , 

The next best step is to visit [New Relic Support](https://support.newrelic.com/), where you can engage the New Relic Support Community or open a support ticket depending on your support level. The support team is best positioned to assist with your specific needs. 

Please provide a link to this GitHub issue when submitting your community post or support ticket. The support team will probably ask for some artefacts like logs as well.

Thanks!

**Comment by nickperry** [comment]
This was caused by https://github.com/containerd/containerd/issues/3667. We discovered some of our nodes did not have `fs.may_detach_mounts = 1`
