### ISSUE TITLE
Error calling include :template

### ISSUE THREAD

**Issue by Yiyito11** [newrelic/nri-kubernetes#673]
### Description
I´m getting this error while tryin to install with a dry-run this helm chart. I´m using the Nri bundle and only enabled: infrastructure, kubeevents, ksm.

![image](https://user-images.githubusercontent.com/23485888/225701083-4ac71722-b9ba-4bdf-ab49-a42d6ab56aa1.png)

But If I go to the configmap and to the helpers.tpl I see that everything looks good. Check here:

![image](https://user-images.githubusercontent.com/23485888/225703388-a9eb0da0-0160-476e-87cc-dffd74048307.png)

![image](https://user-images.githubusercontent.com/23485888/225704457-47c1ae6d-cfdf-4176-9e38-0e692b1c265a.png)

I´m calling this chart locally as you can see (I cloned this repo and copied files locally), as I needed to do some modifications to chart that weren´t not possible calling it to the githubrepo. 
They are just for using our secrets where the license key is located. but nothing related to configmap as issue is described.
 So I removed the secrets.yaml in infrastructure chart, and replaced the chart like following:

![image](https://user-images.githubusercontent.com/23485888/225704921-bd05ecdc-28f7-4205-b0fe-7c0dd1dbfa69.png)

So is there something I´m mising related configmap? or what can be the issue related to the missing template (which I don´t see to be missing)

### Acceptance Criteria
Able to install the NRI bundle with Infrastructure + kubeevents + ksm

### Design Consideration/Limitations
_Why is this the route we should take to achieve our goal?_
_What can't be achieved within this story?_

### Dependencies

NRI Bundle

### Additional context

We are trying to install this chart in our AKS cluster to send metrics to Newrelic cloud instance

**Comment by davidgit** [comment]
Hi , 

The next best step is to visit [New Relic Support](https://support.newrelic.com/), where you can engage the New Relic Support Community or open a support ticket depending on your support level. The support team is best positioned to assist with your specific needs. 

Please provide a link to this GitHub issue when submitting your community post or support ticket.

Thanks!
