### ISSUE TITLE
[Fargate] Document Manual injection

### ISSUE THREAD

**Issue by paologallinaharbur** [newrelic/nri-kubernetes#86]
In case the users do no want to automatically inject the sidecar there should be a clear documentation showing how to do it manually
 - The outcome should be identical to the solution with the automatic injection on.
 - Explain in the FAQ the hybrid solution

Moreover this could be also useful to double check the user experience considering that the only difference should be how the pod was injected

**Comment by paologallinaharbur** [comment]
https://docs.google.com/document/d/1p2t8eJFAnuTcn1Ly-LYRPjW07gJ_mtzxWDO0o5FbtzA/edit

**Comment by invidian** [comment]
Done in https://github.com/newrelic/docs-website/pull/2277?

**Comment by paologallinaharbur** [comment]
Yes!
