### ISSUE TITLE
[Fargate] Automatically inject the sidecar

### ISSUE THREAD

**Issue by paologallinaharbur** [newrelic/nri-kubernetes#87]
This is the most complex feature to be added, we could split this in two or three parts, moreover each point should be parallelizable 

Manual injection of the sidecar would not work in many scenarios, therefore we would need an automatic way to inject automatically such sidecar.

- [x] Find a solution to inject the container only to fargate namespace, following the label selection of the user.
- [ ] Check annotation possibly specifying not to add a sidecar moved to https://github.com/newrelic/newrelic-infra-operator/issues/42
- [x] Find a solution to create and manage certificates
- [x] Inject secrets needed to configure the agent in each fargate managed namespace for the license
- [x] Investigate how to let the container use a working service account (likely create a rolebinding for each existing sa) in the least intrusive way as possible. We would like to remove the old bindings once they are not used anymore
- [ ] Support dryrun Moved to https://github.com/newrelic/newrelic-infra-operator/issues/2

Keep in mind possible permission escalation, that we do not want to reduce the permission of any SA the customer is using.

**In case the injection is failing the user should be able to carry on deploying. However the issue should be visible somewhere**

**Comment by paologallinaharbur** [comment]
Currently we decided not to inject the config map automatically. 
This will be still possible manually.

In the future if integration will at some point configured through annotation will be no longer be an issue

**Comment by invidian** [comment]
General notes about existing Kubernetes issues and limitations with sidecar containers: https://docs.google.com/document/d/1Drw9C_Ljpcr4X9UPLvms1fn8uMRnTfJLb-xipgX4C1M/edit#

**Comment by invidian** [comment]
When do we want to inject the sidecar container? Maybe when:
- Pod is created in namespace with label `X` (Enable injection for all pods in the namespace).
- When Pod has no label `!X` (exclude Pods from injection when injection is **enabled** by default).
- When Pod has label `X`. (Inject when injection is **disabled** by default).

**Comment by paologallinaharbur** [comment]
I would inject the Pod when:
 - It is selected by AKS to run on fargate (checking namespace and the same label selectors of the fargate profile) unless a label specify not to do it.

**Comment by invidian** [comment]
>It is selected by EKS to run on fargate (checking namespace and the same label selectors of the fargate profile) unless a label specify not to do it.

To document what we discussed in more details regarding the injection:
- EKS Fargate requires user to pre-create profiles, which use Namespace name and Pod label selector to choose which Pods should be scheduled on Fargate.
- We ask user to specify the Fargate selector as configuration to the injection webhook. E.g.:
  ```go
  map[string]string{
    "newrelic": "",
    "mynamespace", "app=myapp",
  }
  ```
  It will be up to the user's responsibility to keep Fargate profiles and webhook configuration in sync.
- In addition, we support specifying annotation `X`, which will disable injection on specific pods.

**Comment by invidian** [comment]
After talking to @paologallinaharbur today and some thinking, I would like to suggest we do the following:
- [ ] From the code/deployment perspective:
  - [ ] We may take https://github.com/newrelic/k8s-metadata-injection as a code base.
  - [ ] Running as a Deployment with leader election for controllers for HA.
  - [ ] Deployment should have associated PodDisruptionBudget to support HA.
  - [ ] With pluggable architecture to be able to enable and disable webhooks and controllers.
  - [ ] Deployed as a separate chart which will be part of `nri-bundle` Helm chart.
  - [ ] May eventually incorporate https://github.com/newrelic/k8s-metadata-injection as one of the available webhooks.
  - [ ] In the first iteration without any controllers.
  - [ ] After injection webhook is deployed, Helm `post-install,` hook gracefully restarts (e.g. `kubectl rollout`) webhook server itself to inject agent into itself.
    - [ ] For plain manifest users, either `kubectl rollout` command is provided or Kubernetes Job manifest.
    - [ ] `nri-bundle` may also automatically restart other bundle components to ensure everything is monitored.
    - [ ] Consider using `post-upgrade` as well to roll out changes when webhook version/configuration is updated.
- [ ] From the webhook perspective:
  - [ ] Takes a map of label selectors with namespace name as a key and Pod label selector as a value to follow how Fargate profiles are defined.
    - [ ] What about other Kubernetes serverless offerings like GKE Autopilot? As far as I know, they do not have a concept of profiles.
    - [ ] Using namespace name as a key is limiting and probably done for legacy reasons (e.g. lack of any labels on default namespaces, difficulties in managing labels for namespaces with tools like Helm)
      - From Kubernetes v1.21.0 all namespaces are automatically labelled with `kubernetes.io/metadata.name` label.
      - Would be better to use the `namespaceSelector`/`podSelector` pattern used by `NetworkPolicy`.
        - Can have enabled by default backward compatibility mode for clusters < v1.21.0.
  - [ ] Ensures Secret with a license key is up to date in any namespace where mutated Pod is created. If Secret creation fails, mutation fails as well to ensure optimal resistance against preventing user workloads from scheduling.
    - [ ] We could use `initContainer` as an alternative to fetch the license key Secret from another namespace and put it into a file on `emptyDir` volume?
      - [ ] Seems hacky, as we may need to manage other objects anyway (ServiceAccount, ConfigMap?).
      - [ ] Might be resistant to user deploying workload getting access to license key?
    - [ ] Secrets creation in all namespaces via Helm chart might be problematic, as namespace might not exist (usually monitoring is deployed before other workloads).
  - [ ] Emits warning/error Event when Pod mutation fails.
  - [ ] Injects extra container to Pod configuration with newrelic-infrastructure agent.
  - [ ] Allows users to configure properties of injected newrelic-infrastructure agent, the same way Helm chart does.
    - [ ] Maybe use part of Helm chart values YAML as a snippet?
    - [ ] Can be done automagically with `nri-bundle`.
  - [ ] Ensures all required Pod volumes are part of the Pod specification.
  - [ ] Hash Pod configuration and inject it as a Pod label to be able to identify injection generation?
    - [ ] Label quickly allows to find pods which have agent up to date or which lack agent injection.
  - [ ] Ensures ClusterRoleBinding for agent has listed all monitored Namespaces.
    - [ ] If that fails, injection fails as well.
  - [ ] Monitored workload must use ServiceAccount. We may extend support for dedicated ServiceAccount in the future to lift that limitation.
    - [ ] If pod has mounting service account token disabled or ServiceAccount has token mouting disabled, injection must fail.
  - [ ] Initially ignore integrations_config and config ConfigMaps.
  - [ ] Has permissions to update a single `ClusterRoleBinding` created by Helm Chart.
  - [ ] Has permissions to get, create and update a single `Secret` in cluster-wide.
- [ ] From the controller perspective:
  - [ ] Watching `ClusterRoleBinding` and `Pods` with label `X` for orphan service accounts and cleans them up, together with license `Secret`.
    - [ ] Not relevant in initial implementation.

**Comment by paologallinaharbur** [comment]
I agree on everything the only thing I would specify is that:
 - I would consider as a (really) nice to have the "self-monitoring" feature, but we can wait to implement it during the first iteration. It should not affect any important decision

**Comment by paologallinaharbur** [comment]
We should think also remember to check the [side effect](https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#side-effects-1) in case we are changing the permissions receiving the requests

**Comment by paologallinaharbur** [comment]
An other note, the label seems to be available when intercepted:
```json
{"level":"info","ts":"2021-04-21T16:49:13.727Z","caller":"server/webhook.go:115","msg":"{\"kind\":\"Pod\",\"apiVersion\":\"v1\",\"metadata\":{\"name\":\"nginx\",\"creationTimestamp\":null,\"labels\":{\"eks.amazonaws.com/fargate-profile\":\"fargate\",
```

However we are still not sure if this is a behaviour it is safe to rely on.
It would be better to ask user to add the namespace anyway

**Comment by invidian** [comment]
>We should think also remember to check the side effect in case we are changing the permissions receiving the requests

Good point, I didn't know about the side effects! 

Regarding the following:
>Webhooks that make out-of-band changes ("side effects") must also have a reconciliation mechanism (like a controller) that periodically determines the actual state of the world, and adjusts the out-of-band data modified by the admission webhook to reflect reality.

I think we will need a control loop for `ClusterRoleBinding` then. Secrets don't need it, as Pods are immutable. But if someone tinkers with the `ClusterRoleBinding` by hand, it will break the monitoring.

**Comment by paologallinaharbur** [comment]
Regarding "Check annotation possibly specifying not to add a sidecar"

The operator will be receiving only the request of pods having the AWS label to make sure we are injecting merely on Fargate, 

Then if:
 - The user selected `operator.sidecarInject.always` the sidecar is injected in each pod not belonging to Jobs

Moreover the user can configure the following
 - The user can configure `operator.sidecarInject.includeJobPods` default to false
 - The user can configure `operator.sidecarInject.includePodLabels={}` no effect if `operator.sidecarInject.always` = true (we can add this to the mutation webhook conf)
 - The user can configure `operator.sidecarInject.includeNamespace=[]` no effect if `operator.sidecarInject.always` = true (we can add this to the mutation webhook conf)

Over these options the following will take precedence
 - The user can configure `operator.sidecarInject.excludeAnnotation` with default `newrelic/nri-k8s-operator: include`
 - The user can configure `operator.sidecarInject.includeAnnotation` with default `newrelic/nri-k8s-operator: include`

```
operator:
  sidecarInject:
    enabled: true
    injectAlways: false
    includeJobPods: false
    includePodLabels: [fargate, default]
    includeNamespaces: {"app.kubernetes.io/name" : "demo"}
    excludeAnnotation
```
