### ISSUE TITLE
[Fargate] Document Automatic injection

### ISSUE THREAD

**Issue by paologallinaharbur** [newrelic/nri-kubernetes#89]
- Specify the requirements and the possibility to do it manually if needed
 - Clearly point to the required permissions added when injecting the sidecar
 - Explain how to garbage collect resources
 - Explain that the solution when failing would be NOT a bloker for deployment
 - Explain in the FAQ the hybrid solution

**Comment by invidian** [comment]
Is this still needed?

**Comment by paologallinaharbur** [comment]
yes!
