### ISSUE TITLE
helm chart v3.17.0 results in v3.12.0

### ISSUE THREAD

**Issue by rittneje** [newrelic/nri-kubernetes#896]
I ran `helm template nri-bundle newrelic-infrastructure --repo https://newrelic.github.io/nri-kubernetes --version 3.17.0 --set global.licenseKey=x --set global.cluster='CLUSTER_NAME' --namespace=newrelic --set newrelic-infrastructure.privileged=false --set ksm.enabled=true --set kubeEvents.enabled=false > output.yaml`

Even though I asked for v3.17.0, the output says `app.kubernetes.io/version: 3.12.0`.

If I install v3.22.0, then I get `app.kubernetes.io/version: 3.17.0`.

Clearly there is some discrepancy between the release tags and the versions themselves.

**Comment by juanjjaramillo** [comment]
Helm has the concepts of `version` and `appVersion`:
https://helm.sh/docs/topics/charts/#the-chartyaml-file

What you requested is the Helm chart `newrelic-infrastructure` with `version` 3.17.0, which contains the app `nri-kubernetes` with `appVersion` 3.12.0:
https://github.com/newrelic/nri-kubernetes/blob/newrelic-infrastructure-3.17.0/charts/newrelic-infrastructure/Chart.yaml

If you request the Helm chart `newrelic-infrastructure` with `version` 3.22.0 you get `nri-kubernetes` with `appVersion` 3.17.0:
https://github.com/newrelic/nri-kubernetes/blob/newrelic-infrastructure-3.22.0/charts/newrelic-infrastructure/Chart.yaml

**Comment by rittneje** [comment]
@juanjjaramillo That is needlessly confusing. Please fix the version numbers to be in alignment.
