### ISSUE TITLE
Non-integer values for CADVISOR_PORT break the integration

### ISSUE THREAD

**Issue by roobre** [newrelic/nri-kubernetes#93]
## Description

At the moment, the integration only supports defining the port number in the `CADVISOR_PORT` environment variable, as opposed to a full connection uri as the [kubernetes standard](https://kubernetes.io/docs/concepts/services-networking/service/#environment-variables) dictates.

Adding support for an arbitrarily located cAdvisor can, however, be difficult with the current architecture of the integration.

## Expected Behavior

The integration should support the full format of the `CADVISOR_PORT` env variable or, at least, ignore it if it cannot be handled, rather than blindly appending it to the URL without sanitization:

https://github.com/newrelic/nri-kubernetes/blob/07d5b1e4fccfc849fd0bc38f562d42bb7c077052/src/kubelet/client/discovery.go#L74-L77

**Comment by invidian** [comment]
Considering the comment in code:
>We force to call the standalone cadvisor because k8s < 1.7.6 do not have /metrics/cadvisor kubelet endpoint.

Perhaps we can simply drop support for standalone cadvisor?

**Comment by paologallinaharbur** [comment]
support dropped as suggested
