### ISSUE TITLE
Error in New Relic Infrastructure Window agents

### ISSUE THREAD

**Issue by akshaychopra5207** [newrelic/nri-kubernetes#932]
Facing the issue and error in New Relic Infrastructure Window agents . Metrics are missing.
time="2023-11-07T07:36:56Z" level=error msg="Integration command failed" error="exit status 1" instance=nri-kubernetes integration=com.newrelic.kubernetes prefix=integration/com.newrelic.kubernetes stderr="time=\"2023-11-07T07:36:56Z\" level=panic msg=\"failed to discover nodeIP with kube-state-metrics, got error: pods is forbidden: User \\\"system:serviceaccount:newrelic:nri-bundle-newrelic-infrastructure\\\" cannot list resource \\\"pods\\\" in API group \\\"\\\" at the cluster scope\"\ntime=\"2023-11-07T07:36:56Z\" level=fatal msg=\"failed to discover nodeIP with kube-state-metrics, got error: pods is forbidden: User \\\"system:serviceaccount:newrelic:nri-bundle-newrelic-infrastructure\\\" cannot list resource \\\"pods\\\" in API group \\\"\\\" at the cluster scope\"\n" working-dir="C:\\Program Files\\New Relic\\newrelic-infra\\newrelic-integrations"
## Description
Describe the problem you're encountering.
TIP: Do NOT share sensitive information, whether personal, proprietary, or otherwise! 

## Expected Behavior
No error in the agent logs , metrics should come

## [Troubleshooting](https://discuss.newrelic.com/t/troubleshooting-frameworks/108787) or [NR Diag](https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/troubleshooting/new-relic-diagnostics) results
Provide any other relevant log data.
TIP:  Scrub logs and diagnostic information for sensitive information 

## Steps to Reproduce
Please be as specific as possible.
TIP:  Link a sample application that demonstrates the issue. 

## Your Environment
Include as many relevant details about your environment as possible including the running version of New Relic software and any relevant configurations. 

## Additional context
Add any other context about the problem here. For example, relevant community posts or support tickets.

## For Maintainers Only or Hero Triaging this bug
*Suggested Priority (P1,P2,P3,P4,P5):*
*Suggested T-Shirt size (S, M, L, XL, Unknown):*

**Comment by juanjjaramillo** [comment]
From the error above this is an issue with a [misconfigured ClusterRole object](https://kubernetes.io/docs/reference/access-authn-authz/rbac/):
```
level=fatal msg="failed to discover nodeIP with kube-state-metrics, got error: pods is forbidden: User \"system:serviceaccount:newrelic:nri-bundle-newrelic-infrastructure\" cannot list resource \"pods\" in API group \"\" at the cluster scope"\n" working-dir="C:\Program Files\New Relic\newrelic-infra\newrelic-integrations"
```
