### ISSUE TITLE
Need support for Kubernetes 1.28

### ISSUE THREAD

**Issue by telderfts** [newrelic/nri-kubernetes#940]
### Description
Currently the integration doesn't work with Kubernetes 1.28 which has already had several patch releases. This release has been available for a few months now at least so it would be great for those that need to keep their clusters up to date if compatibility with this version could be completed. Last I saw was that it was compatibile with an RC candidate which has been outdated for a little while now.

**Comment by svetlanabrennan** [comment]
We now support Kubernetes 1.28 with this chart: https://github.com/newrelic/nri-kubernetes/releases/tag/newrelic-infrastructure-3.25.0
